# -*- coding: utf-8 -*-
"""des_gpu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RSSHNihvQZO6MG_d7zG3HsDB1Sb0Yrh
"""

!nvcc --version

from google.colab import files
files.upload()

# Commented out IPython magic to ensure Python compatibility.
# #include <iostream>
# #include <stdint.h>
# #include <chrono>
# %%writefile des_cpu.cpp
# 
# #include<bits/stdc++.h>
# 
# using namespace std;
# 
# #define ROUNDS 16
# 
# uint32_t feistel(uint32_t half, uint64_t key)
# {
#     half ^= (uint32_t)(key);
#     half = ((half << 1) | (half >> 31));
#     return half;
# }
# 
# uint64_t des_encrypt_block(uint64_t block, uint64_t key)
# {
#     uint32_t left = (block >> 32) & 0xFFFFFFFF;
#     uint32_t right = block & 0xFFFFFFFF;
# 
#     for(int i = 0; i < ROUNDS; i++)
#     {
#         uint32_t temp = right;
#         right = left ^ feistel(right, key);
#         left = temp;
#     }
# 
#     return ((uint64_t)right << 32) | left;
# }
# 
# int main()
# {
#     long N = 10000000; // 1e7 blocks for CPU test
#     uint64_t key = 0x133457799BBCDFF1;
# 
#     auto start = chrono::high_resolution_clock::now();
# 
#     for(long i = 0; i < N; i++)
#     {
#         des_encrypt_block(i, key);
#     }
# 
#     auto end = chrono::high_resolution_clock::now();
# 
#     double time = chrono::duration<double>(end - start).count();
# 
#     cout << "CPU Time: " << time << " seconds\n";
#     cout << "Throughput: " << (N / time) << " blocks/sec\n";
# 
#     return 0;
# }

!g++ des_cpu.cpp -O3 -o cpu

!./cpu

!nvcc des_gpu.cu -o des

!./des

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile chacha20_cpu.cpp
# #include <iostream>
# #include <stdint.h>
# #include <chrono>
# using namespace std;
# 
# #define ROUNDS 20
# 
# inline void quarter_round(uint32_t &a, uint32_t &b, uint32_t &c, uint32_t &d)
# {
#     a += b; d ^= a; d = (d << 16) | (d >> 16);
#     c += d; b ^= c; b = (b << 12) | (b >> 20);
#     a += b; d ^= a; d = (d << 8) | (d >> 24);
#     c += d; b ^= c; b = (b << 7) | (b >> 25);
# }
# 
# void chacha20_block(uint32_t state[16])
# {
#     uint32_t working[16];
#     for(int i = 0; i < 16; i++) working[i] = state[i];
# 
#     for(int i = 0; i < ROUNDS; i += 2)
#     {
#         // Column rounds
#         quarter_round(working[0], working[4], working[8], working[12]);
#         quarter_round(working[1], working[5], working[9], working[13]);
#         quarter_round(working[2], working[6], working[10], working[14]);
#         quarter_round(working[3], working[7], working[11], working[15]);
# 
#         // Diagonal rounds
#         quarter_round(working[0], working[5], working[10], working[15]);
#         quarter_round(working[1], working[6], working[11], working[12]);
#         quarter_round(working[2], working[7], working[8], working[13]);
#         quarter_round(working[3], working[4], working[9], working[14]);
#     }
# 
#     for(int i = 0; i < 16; i++)
#         state[i] += working[i];
# }
# 
# int main()
# {
#     long N = 10000000; // blocks
#     uint32_t state[16] = {0};
# 
#     auto start = chrono::high_resolution_clock::now();
# 
#     for(long i = 0; i < N; i++)
#     {
#         state[12] = i; // counter
#         chacha20_block(state);
#     }
# 
#     auto end = chrono::high_resolution_clock::now();
# 
#     double time = chrono::duration<double>(end - start).count();
# 
#     cout << "ChaCha20 CPU\n";
#     cout << "Blocks processed: " << N << endl;
#     cout << "CPU Time: " << time << " seconds\n";
#     cout << "Throughput: " << (N / time) << " blocks/sec\n";
# 
#     return 0;
# }

!g++ chacha20_cpu.cpp -O3 -o chacha_cpu
!./chacha_cpu

# Commented out IPython magic to ensure Python compatibility.
# %%writefile chacha20_gpu.cu
# 
# #include <stdio.h>
# #include <stdint.h>
# #include <cuda.h>
# 
# #define THREADS 256
# #define TOTAL_BLOCKS 1000000000LL
# #define CHUNK_SIZE 1000000LL
# #define ROUNDS 20
# 
# __device__ inline void quarter_round(uint32_t &a, uint32_t &b, uint32_t &c, uint32_t &d)
# {
#     a += b; d ^= a; d = (d << 16) | (d >> 16);
#     c += d; b ^= c; b = (b << 12) | (b >> 20);
#     a += b; d ^= a; d = (d << 8) | (d >> 24);
#     c += d; b ^= c; b = (b << 7) | (b >> 25);
# }
# 
# __device__ void chacha20_block(uint32_t state[16])
# {
#     uint32_t working[16];
#     for(int i = 0; i < 16; i++) working[i] = state[i];
# 
#     for(int i = 0; i < ROUNDS; i += 2)
#     {
#         quarter_round(working[0], working[4], working[8], working[12]);
#         quarter_round(working[1], working[5], working[9], working[13]);
#         quarter_round(working[2], working[6], working[10], working[14]);
#         quarter_round(working[3], working[7], working[11], working[15]);
# 
#         quarter_round(working[0], working[5], working[10], working[15]);
#         quarter_round(working[1], working[6], working[11], working[12]);
#         quarter_round(working[2], working[7], working[8], working[13]);
#         quarter_round(working[3], working[4], working[9], working[14]);
#     }
# 
#     for(int i = 0; i < 16; i++)
#         state[i] += working[i];
# }
# 
# __global__ void chacha_kernel(uint32_t *states, long N)
# {
#     long idx = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     if(idx < N)
#     {
#         uint32_t local_state[16];
#         for(int i = 0; i < 16; i++)
#             local_state[i] = states[idx * 16 + i];
# 
#         local_state[12] = idx;
# 
#         chacha20_block(local_state);
# 
#         for(int i = 0; i < 16; i++)
#             states[idx * 16 + i] = local_state[i];
#     }
# }
# 
# int main()
# {
#     uint32_t *h_states, *d_states;
#     size_t size = CHUNK_SIZE * 16 * sizeof(uint32_t);
# 
#     h_states = (uint32_t*)malloc(size);
#     cudaMalloc(&d_states, size);
# 
#     for(int i = 0; i < CHUNK_SIZE * 16; i++)
#         h_states[i] = i;
# 
#     int blocks = (CHUNK_SIZE + THREADS - 1) / THREADS;
# 
#     cudaEvent_t start, stop;
#     cudaEventCreate(&start);
#     cudaEventCreate(&stop);
# 
#     cudaEventRecord(start);
# 
#     for(long startBlock = 0; startBlock < TOTAL_BLOCKS; startBlock += CHUNK_SIZE)
#     {
#         cudaMemcpy(d_states, h_states, size, cudaMemcpyHostToDevice);
# 
#         chacha_kernel<<<blocks, THREADS>>>(d_states, CHUNK_SIZE);
# 
#         cudaMemcpy(h_states, d_states, size, cudaMemcpyDeviceToHost);
#     }
# 
#     cudaEventRecord(stop);
#     cudaEventSynchronize(stop);
# 
#     float ms = 0;
#     cudaEventElapsedTime(&ms, start, stop);
# 
#     printf("ChaCha20 GPU\n");
#     printf("Processed 1e9 blocks\n");
#     printf("Total GPU Time: %f ms\n", ms);
#     printf("Throughput: %f blocks/sec\n", (TOTAL_BLOCKS * 1000.0) / ms);
# 
#     cudaFree(d_states);
#     free(h_states);
# 
#     return 0;
# }

!nvcc chacha20_gpu.cu -o chacha_gpu
!./chacha_gpu

# Commented out IPython magic to ensure Python compatibility.
# %%writefile salsa20_cpu.cpp
# #include <iostream>
# #include <stdint.h>
# #include <chrono>
# using namespace std;
# 
# #define ROUNDS 20
# 
# inline uint32_t rotl(uint32_t x, int n)
# {
#     return (x << n) | (x >> (32 - n));
# }
# 
# inline void quarter_round(uint32_t &a, uint32_t &b, uint32_t &c, uint32_t &d)
# {
#     b ^= rotl(a + d, 7);
#     c ^= rotl(b + a, 9);
#     d ^= rotl(c + b, 13);
#     a ^= rotl(d + c, 18);
# }
# 
# void salsa20_block(uint32_t state[16])
# {
#     uint32_t x[16];
#     for(int i = 0; i < 16; i++) x[i] = state[i];
# 
#     for(int i = 0; i < ROUNDS; i += 2)
#     {
#         // Column rounds
#         quarter_round(x[0], x[4], x[8], x[12]);
#         quarter_round(x[5], x[9], x[13], x[1]);
#         quarter_round(x[10], x[14], x[2], x[6]);
#         quarter_round(x[15], x[3], x[7], x[11]);
# 
#         // Row rounds
#         quarter_round(x[0], x[1], x[2], x[3]);
#         quarter_round(x[5], x[6], x[7], x[4]);
#         quarter_round(x[10], x[11], x[8], x[9]);
#         quarter_round(x[15], x[12], x[13], x[14]);
#     }
# 
#     for(int i = 0; i < 16; i++)
#         state[i] += x[i];
# }
# 
# int main()
# {
#     long N = 10000000; // number of blocks
#     uint32_t state[16] = {0};
# 
#     auto start = chrono::high_resolution_clock::now();
# 
#     for(long i = 0; i < N; i++)
#     {
#         state[8] = i; // counter
#         salsa20_block(state);
#     }
# 
#     auto end = chrono::high_resolution_clock::now();
# 
#     double time = chrono::duration<double>(end - start).count();
# 
#     cout << "Salsa20 CPU\n";
#     cout << "Blocks processed: " << N << endl;
#     cout << "CPU Time: " << time << " seconds\n";
#     cout << "Throughput: " << (N / time) << " blocks/sec\n";
# 
#     return 0;
# }

!g++ salsa20_cpu.cpp -O3 -o salsa_cpu
!./salsa_cpu

# Commented out IPython magic to ensure Python compatibility.
# %%writefile salsa20_gpu.cu
# #include <stdio.h>
# #include <stdint.h>
# #include <cuda.h>
# 
# #define THREADS 256
# #define TOTAL_BLOCKS 1000000000LL
# #define CHUNK_SIZE 1000000LL
# #define ROUNDS 20
# 
# __device__ inline uint32_t rotl(uint32_t x, int n)
# {
#     return (x << n) | (x >> (32 - n));
# }
# 
# __device__ inline void quarter_round(uint32_t &a, uint32_t &b, uint32_t &c, uint32_t &d)
# {
#     b ^= rotl(a + d, 7);
#     c ^= rotl(b + a, 9);
#     d ^= rotl(c + b, 13);
#     a ^= rotl(d + c, 18);
# }
# 
# __device__ void salsa20_block(uint32_t state[16])
# {
#     uint32_t x[16];
#     for(int i = 0; i < 16; i++) x[i] = state[i];
# 
#     for(int i = 0; i < ROUNDS; i += 2)
#     {
#         quarter_round(x[0], x[4], x[8], x[12]);
#         quarter_round(x[5], x[9], x[13], x[1]);
#         quarter_round(x[10], x[14], x[2], x[6]);
#         quarter_round(x[15], x[3], x[7], x[11]);
# 
#         quarter_round(x[0], x[1], x[2], x[3]);
#         quarter_round(x[5], x[6], x[7], x[4]);
#         quarter_round(x[10], x[11], x[8], x[9]);
#         quarter_round(x[15], x[12], x[13], x[14]);
#     }
# 
#     for(int i = 0; i < 16; i++)
#         state[i] += x[i];
# }
# 
# __global__ void salsa_kernel(uint32_t *states, long N)
# {
#     long idx = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     if(idx < N)
#     {
#         uint32_t local_state[16];
# 
#         for(int i = 0; i < 16; i++)
#             local_state[i] = states[idx * 16 + i];
# 
#         local_state[8] = idx;
# 
#         salsa20_block(local_state);
# 
#         for(int i = 0; i < 16; i++)
#             states[idx * 16 + i] = local_state[i];
#     }
# }
# 
# int main()
# {
#     uint32_t *h_states, *d_states;
#     size_t size = CHUNK_SIZE * 16 * sizeof(uint32_t);
# 
#     h_states = (uint32_t*)malloc(size);
#     cudaMalloc(&d_states, size);
# 
#     for(int i = 0; i < CHUNK_SIZE * 16; i++)
#         h_states[i] = i;
# 
#     int blocks = (CHUNK_SIZE + THREADS - 1) / THREADS;
# 
#     cudaEvent_t start, stop;
#     cudaEventCreate(&start);
#     cudaEventCreate(&stop);
# 
#     cudaEventRecord(start);
# 
#     for(long startBlock = 0; startBlock < TOTAL_BLOCKS; startBlock += CHUNK_SIZE)
#     {
#         cudaMemcpy(d_states, h_states, size, cudaMemcpyHostToDevice);
# 
#         salsa_kernel<<<blocks, THREADS>>>(d_states, CHUNK_SIZE);
# 
#         cudaMemcpy(h_states, d_states, size, cudaMemcpyDeviceToHost);
#     }
# 
#     cudaEventRecord(stop);
#     cudaEventSynchronize(stop);
# 
#     float ms = 0;
#     cudaEventElapsedTime(&ms, start, stop);
# 
#     printf("Salsa20 GPU\n");
#     printf("Processed 1e9 blocks\n");
#     printf("Total GPU Time: %f ms\n", ms);
#     printf("Throughput: %f blocks/sec\n", (TOTAL_BLOCKS * 1000.0) / ms);
# 
#     cudaFree(d_states);
#     free(h_states);
# 
#     return 0;
# }

!nvcc salsa20_gpu.cu -o salsa_gpu
!./salsa_gpu

# Commented out IPython magic to ensure Python compatibility.
# %%writefile des_ctr_cpu.cpp
# #include <iostream>
# #include <stdint.h>
# #include <chrono>
# using namespace std;
# 
# #define ROUNDS 16
# 
# uint32_t feistel(uint32_t half, uint64_t key)
# {
#     half ^= (uint32_t)(key);
#     half = ((half << 1) | (half >> 31));
#     return half;
# }
# 
# uint64_t des_encrypt_block(uint64_t block, uint64_t key)
# {
#     uint32_t left = (block >> 32) & 0xFFFFFFFF;
#     uint32_t right = block & 0xFFFFFFFF;
# 
#     for(int i = 0; i < ROUNDS; i++)
#     {
#         uint32_t temp = right;
#         right = left ^ feistel(right, key);
#         left = temp;
#     }
# 
#     return ((uint64_t)right << 32) | left;
# }
# 
# int main()
# {
#     long N = 10000000;
#     uint64_t key = 0x133457799BBCDFF1;
#     uint64_t nonce = 0xABCDEF;
# 
#     auto start = chrono::high_resolution_clock::now();
# 
#     for(long i = 0; i < N; i++)
#     {
#         uint64_t counter = nonce + i;
#         uint64_t keystream = des_encrypt_block(counter, key);
#         uint64_t plaintext = i;
#         uint64_t ciphertext = plaintext ^ keystream;
#     }
# 
#     auto end = chrono::high_resolution_clock::now();
# 
#     double time = chrono::duration<double>(end - start).count();
# 
#     cout << "DES CTR CPU\n";
#     cout << "Blocks: " << N << endl;
#     cout << "CPU Time: " << time << " sec\n";
#     cout << "Throughput: " << (N / time) << " blocks/sec\n";
# 
#     return 0;
# }

!g++ des_ctr_cpu.cpp -O3 -o des_ctr_cpu
!./des_ctr_cpu

# Commented out IPython magic to ensure Python compatibility.
# %%writefile des_ctr_gpu.cu
# #include <stdio.h>
# #include <stdint.h>
# #include <cuda.h>
# 
# #define THREADS 256
# #define TOTAL_BLOCKS 1000000000LL
# #define CHUNK_SIZE 1000000LL
# #define ROUNDS 16
# 
# __device__ uint32_t feistel(uint32_t half, uint64_t key)
# {
#     half ^= (uint32_t)(key);
#     half = ((half << 1) | (half >> 31));
#     return half;
# }
# 
# __device__ uint64_t des_encrypt_block(uint64_t block, uint64_t key)
# {
#     uint32_t left = (block >> 32) & 0xFFFFFFFF;
#     uint32_t right = block & 0xFFFFFFFF;
# 
#     for(int i = 0; i < ROUNDS; i++)
#     {
#         uint32_t temp = right;
#         right = left ^ feistel(right, key);
#         left = temp;
#     }
# 
#     return ((uint64_t)right << 32) | left;
# }
# 
# __global__ void des_ctr_kernel(uint64_t *plaintext,
#                                uint64_t *ciphertext,
#                                uint64_t key,
#                                uint64_t nonce,
#                                long N)
# {
#     long idx = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     if(idx < N)
#     {
#         uint64_t counter = nonce + idx;
#         uint64_t keystream = des_encrypt_block(counter, key);
#         ciphertext[idx] = plaintext[idx] ^ keystream;
#     }
# }
# 
# int main()
# {
#     uint64_t key = 0x133457799BBCDFF1;
#     uint64_t nonce = 0xABCDEF;
# 
#     uint64_t *h_plain, *h_cipher;
#     uint64_t *d_plain, *d_cipher;
# 
#     size_t size = CHUNK_SIZE * sizeof(uint64_t);
# 
#     h_plain = (uint64_t*)malloc(size);
#     h_cipher = (uint64_t*)malloc(size);
# 
#     cudaMalloc(&d_plain, size);
#     cudaMalloc(&d_cipher, size);
# 
#     int blocks = (CHUNK_SIZE + THREADS - 1) / THREADS;
# 
#     cudaEvent_t start, stop;
#     cudaEventCreate(&start);
#     cudaEventCreate(&stop);
# 
#     cudaEventRecord(start);
# 
#     for(long startBlock = 0; startBlock < TOTAL_BLOCKS; startBlock += CHUNK_SIZE)
#     {
#         for(long i = 0; i < CHUNK_SIZE; i++)
#             h_plain[i] = startBlock + i;
# 
#         cudaMemcpy(d_plain, h_plain, size, cudaMemcpyHostToDevice);
# 
#         des_ctr_kernel<<<blocks, THREADS>>>(d_plain, d_cipher, key, nonce, CHUNK_SIZE);
# 
#         cudaMemcpy(h_cipher, d_cipher, size, cudaMemcpyDeviceToHost);
#     }
# 
#     cudaEventRecord(stop);
#     cudaEventSynchronize(stop);
# 
#     float ms;
#     cudaEventElapsedTime(&ms, start, stop);
# 
#     printf("DES CTR GPU\n");
#     printf("Processed 1e9 blocks\n");
#     printf("GPU Time: %f ms\n", ms);
#     printf("Throughput: %f blocks/sec\n", (TOTAL_BLOCKS * 1000.0) / ms);
# 
#     cudaFree(d_plain);
#     cudaFree(d_cipher);
#     free(h_plain);
#     free(h_cipher);
# 
#     return 0;
# }

!nvcc des_ctr_gpu.cu -o des_ctr_gpu
!./des_ctr_gpu